name: CI

on:
  push:
    branches: main
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Build
        run: CGO_ENABLED=0 go build -o app

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: gustjd887/go-bookinfo-productpage
          tags: |
            type=sha
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Github Helm Colne
        uses: actions/checkout@v3
        with:
          repository: gustjd887/go-bookinfo-helm
          ref: main
          path: helm

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'go-bookinfo-productpage/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.meta.outputs.tags }}
          branch: main
          targetBranch: main
          createPR: false
          message: 'Update Image Version to ${{ steps.meta.outputs.tags }}'
          workdir: helm

      - run: git push
      